refactor: use dojoup to download and install versions

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -5,7 +5,29 @@ set -euo pipefail
 current_script_path=${BASH_SOURCE[0]}
 plugin_dir=$(dirname "$(dirname "$current_script_path")")
 
+TOOL_BINS=(sozo katana torii dojo-language-server)
+
 # shellcheck source=./lib/utils.bash
 source "${plugin_dir}/lib/utils.bash"
 
-install_version "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH"
+install_path="${ASDF_INSTALL_PATH%/bin}/bin"
+
+if [ "${ASDF_INSTALL_TYPE}" != "version" ]; then
+    fail "asdf-${TOOL_NAME} supports release installs only"
+fi
+
+(
+    mkdir -p "$install_path"
+    cp -r "${ASDF_DOWNLOAD_PATH}"/bin/* "${install_path}"
+
+    # Ensure all binaries exist and executable
+    for bin in "${TOOL_BINS[@]}"; do
+        test -x "${install_path}/${bin}" || fail "Expected ${install_path}/${bin} to be executable."
+    done
+
+    echo "${TOOL_NAME} ${ASDF_INSTALL_VERSION} installation was successful!"
+
+) || (
+    rm -rf "$install_path"
+    fail "An error occurred while installing ${TOOL_NAME} ${ASDF_INSTALL_VERSION}."
+)
